version: '1.0.0'
services:
  eureka-server:
    build: 
      context: eureka-server/
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
  api-gateway:
    build: 
      context: api-gateway/
      dockerfile: Dockerfile
    image: api-gateway:latest
    ports:
      - "9090:9090"
    networks:
      - spring-cloud-network
    depends_on: 
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://student-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: student-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]_NAME: Path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]_ARG[PATTERN]: /api/student/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://mentor-service:8083
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: mentor-service
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]_NAME: Path
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]_ARG[PATTERN]: /api/mentor/**
  mentor-service:
    platform: linux/x86_64
    build: 
      context: mentor-service/
      dockerfile: Dockerfile
    image: mentor-service:latest
    restart: on-failure
    env_file: ./.env
    ports:
      - 8083:8083
    networks:
      - spring-cloud-network
    depends_on:
    - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE = http://eureka-server:8761/eureka    
      - SPRING_CLOUD_GATEWAY_URI = http://api-gateway:9090
      - SPRING_DATASOURCE_JDBC-URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  student-service:
    platform: linux/x86_64
    build: 
      context: student-service/
      dockerfile: Dockerfile
    image: student-service:latest
    ports:
      - 8081:8081
    depends_on:
      - eureka-server
      - api-gateway
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka-server:8761/eureka    
      - SPRING_CLOUD_GATEWAY_URI= http://api-gateway:9090
      - SPRING_DATASOURCE_JDBC-URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - '14250'
      - '14268'
  otel-collector:
    image: otel/opentelemetry-collector:0.72.0
    command:
      - --config=/etc/otel-collector-config.yml
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - jaeger-service
  mysqldb:
    container_name: mysqldb
    volumes:
      - mysqldb:/var/lib/mysql
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
networks:
  spring-cloud-network:
      driver: bridge
volumes:
  mysqldb: