receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
        endpoint: collector:4318
processors:
  batch:
exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
extensions:
  health_check:
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
